using EdgeTtsSharp;

namespace ConsoleApp1;

class Program
{
    static async Task Main(string[] args)
    {
        var voice = await EdgeTts.GetVoice("en-US-AriaNeural");
        await voice.SaveAudioToFile(
            "This is a test of audio generated by EdgeTTS. The stream cohesion is tested by comparing the MD5 hash of the stream to a known value. It is expected to encounter slight deviations, but the audio quality should not be affected."
            , "C:\\Users\\g4m3r\\source\\repos\\EdgeTtsSharp\\ConsoleApp1\\bin\\Debug\\audio.mp3");

        Console.WriteLine("Hello, World!");
        Console.ReadLine();
    }
}